gitConfig:
  pull.rebase: "true"

ports:
  - port: 8080 # Vue CLI
    onOpen: ignore
  - port: 8000 # Django runserver
    onOpen: ignore
    visibility: public
  - port: 3000 # Vite
    onOpen: ignore
  - port: 5432 # PostgreSQL
    onOpen: ignore
  - port: 6379 # Redis
    onOpen: ignore

tasks:
  - name: Node.js
    init: yarn --cwd $GITPOD_REPO_ROOT/frontend/ install
    command: |
      echo 'export PROXY_URL=$(gp url 8000)' >> ~/.bashrc
      gp sync-done api-proxy-url
      source ~/.bashrc

  - name: Python
    openMode: split-right
    command: |
      gp sync-await api-proxy-url
      source ~/.bashrc
      pip freeze | xargs pip uninstall -y
      pip install -r $GITPOD_REPO_ROOT/backend/deploy/requirements.txt
      echo `cat /dev/urandom | head -1 | md5sum | head -c 32` > $GITPOD_REPO_ROOT/backend/data/config/secret.key
      python3 $GITPOD_REPO_ROOT/backend/manage.py migrate
      python3 $GITPOD_REPO_ROOT/backend/manage.py inituser --username=root --password=rootroot --action=create_super_admin

  - name: DB Container
    openMode: tab-before
    command: |
      gp sync-await api-proxy-url
      source ~/.bashrc
      docker-compose -f $GITPOD_REPO_ROOT/.gitpod.docker-compose.yml up -d

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - donjayamanne.githistory
    - eamodio.gitlens
    - editorconfig.editorconfig
    - gruntfuggly.todo-tree
    - humao.rest-client
    - johnsoncodehk.volar
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
    - naumovs.color-highlight
    - oderwat.indent-rainbow
    - pkief.material-icon-theme
