# Generated by Django 3.2.12 on 2023-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileResult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeprofile',
            name='hits',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='codeprofile',
            name='per_hit',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='codeprofile',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
