# Generated by Django 3.2.12 on 2023-05-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileResult', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeprofile',
            name='increment',
        ),
        migrations.RemoveField(
            model_name='codeprofile',
            name='line_m',
        ),
    ]
