# Generated by Django 3.2.12 on 2023-05-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileResult', '0002_auto_20230528_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeprofile',
            name='per_hit',
        ),
    ]
