# Generated by Django 4.1.7 on 2023-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20211030_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'problem_solved',
            },
        ),
    ]
