name: Frontend Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/test-frontend.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache Node modules
        id: cache-yarn
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
            ./frontend/public
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node packages
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        working-directory: ${{ env.working-directory }}
        run: yarn install

      - name: Check styles
        working-directory: ${{ env.working-directory }}
        run: yarn lint --no-fix

      - name: Build production files
        working-directory: ${{ env.working-directory }}
        run: yarn build
